name: Sync CV

on:
  workflow_dispatch:


env:
  CV_ASSET_PATH: "docs/assets/Eytan-Ohana-Resume.pdf"


jobs:
  sync:
    runs-on: ubuntu-latest

    outputs:
      changed: ${{ steps.detect.outputs.changed }}
      deploy_ref: ${{ steps.setref.outputs.deploy_ref }}

    permissions:
      contents: write # to commit back into the website repo

    steps:
      - name: Checkout website repo
        uses: actions/checkout@v4

      - name: Checkout private resume repo
        uses: actions/checkout@v4
        with:
          repository: eytanohana/Personal-Info
          ref: master
          token: ${{ secrets.SYNC_CV_PERSONAL_INFO_TOKEN }}
          path: _resume_repo

      - name: Copy latest resume files into website repo
        run: |
          mkdir -p docs/assets
          cp "_resume_repo/resumes/Eytan-Ohana-Resume.pdf"  ${{ env.CV_ASSET_PATH }}

      - name: Detect changes
        id: detect
        run: |
          if git diff --quiet; then
            echo "no changes"
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changes detected"
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit & push if changed
        if: steps.detect.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add ${{ env.CV_ASSET_PATH }}
          git commit -m "[bot]: sync latest resume"
          git push

      - name: Set deploy ref (new HEAD sha)
        id: setref
        run: |
          echo "deploy_ref=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

  deploy:
    needs: sync
    if: needs.sync.outputs.changed == 'true'
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      ref: ${{ needs.sync.outputs.deploy_ref }}
